version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mascotasGoAdmin
      POSTGRES_DB: mascotasGoUser
    ports:
      - 5432:5432