services:
  auth:
    container_name: AuthService
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    environment:
      - USER_URL=${USER_URL}
    networks:
       auth_networks:
         aliases: 
          - AuthService
networks:
  auth_networks:
    name: MascotasGo_Network
    driver: bridge
    ipam:
      driver: default
    external: true

